Lambda is rebuilt and API Gateway redeploy

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -68,6 +68,11 @@ jobs:
         run: |
           terraform import aws_api_gateway_resource.proxy je1gx4u3o8/8vmcnx || echo "Proxy resource not found — skipping"
 
+      - name: 🛠 Import existing ANY method on {proxy+} if it exists
+        run: |
+          terraform import aws_api_gateway_method.proxy je1gx4u3o8/8vmcnx/ANY || echo "Method not found — skipping"
+
+
       - name: ✅ Terraform Apply (local environment)
         run: |
           echo "Setting TF_VAR_env_vars"
