Lambda is rebuilt and API Gateway redeploy

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -64,6 +64,10 @@ jobs:
         run: |
           terraform import aws_api_gateway_rest_api.api je1gx4u3o8 || echo "API not found — skipping"
 
+      - name: 🛠 Import existing API Gateway stage if it exists
+        run: |
+          terraform import aws_api_gateway_stage.stage je1gx4u3o8/local || echo "Stage not found — skipping"
+
       - name: 🛠 Import existing proxy resource if it exists
         run: |
           terraform import aws_api_gateway_resource.proxy je1gx4u3o8/8vmcnx || echo "Proxy resource not found — skipping"
@@ -71,7 +75,6 @@ jobs:
       - name: 🛠 Import existing ANY method on {proxy+} if it exists
         run: |
           terraform import aws_api_gateway_method.proxy je1gx4u3o8/8vmcnx/ANY || echo "Method not found — skipping"
-
 
       - name: ✅ Terraform Apply (local environment)
         run: |
